name: Node.js CI

# Definir en qué eventos se ejecuta el workflow
on:
  push:
    branches:
      - main  # Ejecutar en push a la rama main
  pull_request:
    branches:
      - main  # Ejecutar en pull requests hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository content
        uses: actions/checkout@v3  # Actualizado a v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Actualizado a v3
        with:
          node-version: '20.x'  # Especifica la versión de Node.js (Node 20)

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar el script de build (aunque solo imprime un mensaje)
      - name: Build project
        run: npm run build

      # Paso 5: Ejecutar el servidor y detenerlo después de unos segundos
      - name: Start project
        run: |
          npm start &
          sleep 5  # Mantiene el servidor ejecutándose durante 5 segundos
          kill $!  # Luego lo detiene para no bloquear el workflow

      # Paso 6 (Opcional): Ejecutar pruebas (si las tienes definidas)
      # Como no tienes pruebas definidas, este paso solo imprimirá el mensaje definido en el script
      - name: Run tests
        run: npm test
